Improve expression C++ interface
FEniCS/ffcx pull request #453
Opened 2022-02-03 17:08 UTC by jorgensd

Extend expression interface to allow `ufl.FiniteElementBase` as input arguments (except MixedSpaces).
This avoid manual definitions of interpolation points, which in turn can be used to compute secondary variables without projections.

A typical `.ufl` file would look like:
```python
cell = triangle
v_el = VectorElement("Lagrange", cell, 1)
mesh = Mesh(v_el)

el = FiniteElement("CG", cell, 2)
el_int = VectorElement("Discontinuous Lagrange", cell, 1)
me = MixedElement([el, el_int])
V = FunctionSpace(mesh, me)
u = Coefficient(V)

du0 = grad(u[0])
du1 = grad(u[1])

q_el = FiniteElement("Quadrature", cell, 3, quad_scheme="default")
Q = FunctionSpace(mesh, q_el)
q = Coefficient(Q)
powq = 3*q**2

expressions = [(du0, el), (du1, el_int), (powq, q_el)]
```

2022-02-03 17:10 UTC, jorgensd commented on ffcx/ir/representation.py
> +        points = expression[1]
```suggestion
        points = numpy.asarray(expression[1])
```

2022-02-03 17:11 UTC, jorgensd commented on ffcx/ir/representation.py
> +    # If the second element argument of the Expression tuple is an ufl.FiniteElement,
```suggestion
    # If the second element argument of the Expression tuple is defined as a finite element from ufl,
    # get the corresponding interpolation points
```

2022-02-03 20:09 UTC, jhale approved these changes

2022-02-04 12:15 UTC, michalhabera requested changes

2022-02-04 12:15 UTC, michalhabera commented on ffcx/analysis.py
> +            if isinstance(ufl_object[1], ufl.FiniteElementBase):
I would suggest you create basix element and fetch points at this point. It is more error-prone if we keep this generic tuple for too long in the pipeline.

2022-02-04 12:15 UTC, michalhabera commented on ffcx/ir/representation.py
> +    if isinstance(expression[1], ufl.FiniteElementBase):
This will be simpler if you move it to analysis.py (see comment above).

2022-02-04 13:16 UTC, michalhabera approved these changes

2022-02-04 13:36 UTC, jorgensd commented
Changes suggested by @michalhabera  has not implemented as it breaks the hashing of the expression.

2022-02-05 12:45 UTC, michalhabera commented
I am happy with this, but in longer terms we'll need to formalise notion of "expression with evaluation points", so tuple of multivalued type isn't entering the interface. Any comments @garth-wells ?

2022-02-05 21:06 UTC, garth-wells commented
> I am happy with this, but in longer terms we'll need to formalise notion of "expression with evaluation points", so tuple of multivalued type isn't entering the interface. Any comments @garth-wells ?

The line
```
expressions = [(du0, el), (du1, el_int), (powq, q_el)]
```
looks cryptic to me. Could `namedtuple` or something else make it clearer?

2022-02-07 17:47 UTC, jorgensd commented
> `namedtuple`

Im not sure how namedtuple would help here. It is simply a list of tuples (ufl_expression, ufl_element), where we want to generate code for evaluating the `ufl_expression` at the interpolation points of the `ufl_element`.

2022-02-21 15:21 UTC, garth-wells commented
@jorgensd now that we're using 'plain' .py files, could you try getting the same functionality by importing a Basix element? It wouldn't be a completely smooth interface just yet, but I think the more programmatic approach will serve us better going forward.

2022-02-21 16:43 UTC, jorgensd commented
Superseded by #463

2022-02-21 16:43 UTC, closed without merging