Add demo for interpolating expressions
FEniCS/ffcx pull request #463
Opened 2022-02-21 16:43 UTC by jorgensd

Superseding #453, using `basix` to obtain interpolation/quadrature points to generate integration kernels for various expressions that can be used for interpolation in C++.

2022-02-21 16:43 UTC, jorgensd commented on demo/test_demos.py
> +        "_TensorProductElement",
```suggestion
        "_TensorProductElement"
```

2022-02-22 12:01 UTC, michalhabera approved these changes
Looks good, I think you can remove `GradExpression.py` demo. This demo is superset of it, we need to keep demos low, too many already.

2022-02-22 12:31 UTC, merged

2022-02-22 12:40 UTC, garth-wells requested changes
Looks good.

I found readability a little challenging in parts. I've left some suggestions to reduce the number of variables and to change some names.

2022-02-22 12:40 UTC, garth-wells commented on demo/ExpressionInterpolation.py
> +# Copyright (C) 2022 Jørgen S. Dokken
Use the short SPDX license header.

2022-02-22 12:40 UTC, garth-wells commented on demo/ExpressionInterpolation.py
> +v_el = VectorElement("Lagrange", cell, 1)
I'd suggest reducing the number of variables to improve readabilty, e.g.
```python
mesh = Mesh(VectorElement("Lagrange", cell, 1))
```

2022-02-22 12:40 UTC, garth-wells commented on demo/ExpressionInterpolation.py
> +me = MixedElement([el, el_int])
```python
element = MixedElement([FiniteElement("Lagrange", cell, 2), VectorElement("Discontinuous Lagrange", cell, 1)])
```

2022-02-22 12:40 UTC, garth-wells commented on demo/ExpressionInterpolation.py
> +b_rule = basix.quadrature.string_to_type(q_rule)
Can `q_rule` and `q_degree` be gotten directly from `q_el`?

2022-02-22 12:40 UTC, garth-wells commented on demo/ExpressionInterpolation.py
> +b_element = basix.create_element(family, b_cell, 4, basix.LagrangeVariant.gll_warped, True)
What is the parameter `4`?

2022-02-22 12:40 UTC, garth-wells commented on demo/ExpressionInterpolation.py
> +interpolation_points = b_element.points
`X = b_element.points`